In [ ]:
#learndataa learndataa learndataa learndataa learndataa learndataa learndataa learndataa learndataa

## Exercises

### For Beginners: 5. Arrays (Part I) in Python

#### Total questions sets: 6
#### Estimated time required: upto 60 minutes

[Notes: 
- Answers may be typed after the line "#-------#" in each cell. Additional cells may be created if needed.
- The estimated time required to complete the exercise may vary depending on your prior knowledge.
- Answers to the questions are posted at the end of this worksheet. However, to help you learn, it is suggested that you to try to answer the questions yourself before looking at the answers.
]

### Import libraries

In [1]:
import numpy as np
import pandas as pd

### Question 0:
- Create any 1-D (i.e. one dimensional) and 2-D array
- Create a zeros and ones array for size(3,4)
- Create an array of size (5,3) that has value of 999 only
- Create a 4x4 array of random floats betwee 0 and 1
- Create a 1-D array using .arange(), .linspace() with 5 elements each
- Create an array from a list [5.96, 39.94, 22.34]

Print all answers to output

[Note: Create new variables of your choice as needed.]

In [ ]:
# ------- type the answer below this line ------- #



### Question # 1:  
In the array given:
- Find the index for the element of value 2
- Find its shape, size, type and dtype
- Slice the array to create a 2x2 array with elements 30, 40, 300 and 400
- Slice the array to get elements from column at index 2 onwards and all rows
- Slice the array to get elements from row at index 1 onwards and all columns
- Slice the array to get all columns and only top two rows
- Slice the array to get row at index 2 and columns at index 1 and 2 only only

Print all answers to output

[Note: Create new variables of your choice as needed.]

In [ ]:
a = np.array([[1, 2, 3, 4], [10, 20, 30, 40], [100, 200, 300, 400]])

# ------- type the answer below this line ------- #



### Question # 2: 
- Compute the elementwise sum of two arrays below
- Compute the elementwise multiplication of two arrays below
- Use two arrays given to compute an output array np.array([[0.1 , 0.2 ],[0.05, 0.1 ]])

Print all answers to output

[Note: Create new variables of your choice as needed.]

In [ ]:
p1 = np.array([[1,2], [1,2]])
p2 = np.array([[10, 10], [20, 20]])


# ------- type the answer below this line ------- #




### Question # 3:
- Find the index for the min and max numbers in the array for axis=0 and axis=1
- Create a subset of the array as: np.array([[8,6],[2,11]]) (Hint: use slicing and square root)

Print all answers to output

[Note: Create new variables of your choice as needed.]

In [ ]:
a = np.array([[1,22,3.4,56,9],
              [34,23,64,36,2],
              [6,8,4,121,6]
             ])

# ------- type the answer below this line ------- #



### Question # 4:
Imagine the array given below is the average customer rating data.
Here, each column represents day of the week and
each row represents the hotel chain in the Sky-city.
Assuming that you reach that Sky-city on a Wednesday, 
which hotel could you find that has the highest customer rating? 

Rating scale:
1(bad) ... to ... 5 (excellent)

Print all answers to output

[Note: Create new variables of your choice as needed.]

In [ ]:
customer_rating = np.array([
    [3.5, 4.9, 2.3, 5.0, 1.0, 3.4, 4.4], # Hotel Panorama
    [0.5, 3.9, 1.3, 4.0, 5.0, 4.4, 2.4], # Hotel Galactica
    [4.5, 1.9, 3.3, 4.0, 5.0, 3.9, 2.3], # Hotel Noname
    [1.1, 3.9, 4.1, 3.9, 4.3, 4.7, 2.1], # Hotel Seaby
    [5.0, 5.0, 1.1, 1.1, 2.4, 4.9, 2.3], # Hotel Drive
    [4.5, 3.4, 3.3, 4.8, 4.4, 3.3, 3.1], # Hotel Paradise
   # Mon. Tue. Wed. Thu. Fri. Sat. Sun  
])
# ------- type the answer below this line ------- #



### Question # 5:

#### Story:
A new business'CrunchyRoads' in the city is in the final stages of a contract with one of five local airports.  
The contract would allow CrunchyRoads to get cheaper air-tickets for their employees.
They need to choose only one airport. The company also wishes to choose an airport that is closest to their headquarter. Because it would reduce the commute time for their staff and thus reduce travel cost. They have hired you as an analyst to find them a closest airport.

#### Your approach:
- In the array given below there are latitude and longitude for 5 airports
- Column at Index#0 is latitude and Index#1 is longitude [Hint: Here, think of this as x (latitude) and y (longitude) coordinates.]
- To calculate the distance between two points (x1,y1) and (x2,y2) the formula is: 
  - square root of (x2 - x2)**2 + (y2 - y1)**2


[Note: Solve without using a 'for loop'.]


Print all answers to output.

[Note: Create new variables of your choice as needed.]

In [ ]:
airports_xy_cord = np.array([
    [10.5, 11.0], # Airport Superfast
    [5.9,15.6],   # Airport Timfly
    [13.8, 7.7],  # Airport Artsky
    [8.0,8.0],    # Airport Whereto
    [12.6,2.1]    # Airport Tonowhere
   # x.    y. 
])

crunchy_roads_cord = np.array(1,1)

# ------- type the answer below this line ------- #



### ////////////////////////////////////////////////////////////////////////////////////////////////////////
### ////////////////////////////////////////////////////////////////////////////////////////////////////////
### For practice, please try the questions above before looking at the answers below
### ////////////////////////////////////////////////////////////////////////////////////////////////////////
### ////////////////////////////////////////////////////////////////////////////////////////////////////////

# Answers
[Note: There may be different ways to answer the same question. Therefore, it is okay if the answers vary and sometimes do not match exactly.]

### Question 0:
- Create any 1-D (i.e. one dimensional) and 2-D array
- Create a zeros and ones array for size(3,4)
- Create an array of size (5,3) that has value of 999 only
- Create a 4x4 array of random floats betwee 0 and 1
- Create a 1-D array using .arange(), .linspace() with 5 elements each
- Create an array from a list [5.96, 39.94, 22.34]

Print all answers to output

[Note: Create new variables of your choice as needed.]

In [3]:
# ------- type the answer below this line ------- #

# Answer # 1:
one_d_array = np.array([1,2,3])
print("1D array: ", one_d_array, "\n") # Note: "\n" is added to create a new line

# Answer # 2:
a_zeros = np.zeros((3,4))
a_ones = np.ones((3,4))
print("Zeros: \n", a_zeros,"\n", "Ones: \n", a_ones,"\n")

# Answer # 3:
a_full = np.full((5,3), 999)
print("Full:\n", a_full)

# Answer # 4:
a_random = np.array(np.random.random((2,2)))
print("Random:\n",a_random)
print("\n") # create a new line


# Answer # 5:
a_arange = np.array(np.arange(0,5))
a_linspace = np.array(np.linspace(0,5,5))
print("arange:\n", a_arange, "\n", "linspace:\n", a_linspace, "\n")

# Answer # 6:
a_list = [5.96, 39.94, 22.34]
a_array = np.array(a_list)
print("List to array:\n", a_array, " Type:", type(a_array))

1D array:  [1 2 3] 

Zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 
 Ones: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

Full:
 [[999 999 999]
 [999 999 999]
 [999 999 999]
 [999 999 999]
 [999 999 999]]
Random:
 [[0.74465664 0.94650702]
 [0.94233833 0.29209361]]


arange:
 [0 1 2 3 4] 
 linspace:
 [0.   1.25 2.5  3.75 5.  ] 

List to array:
 [ 5.96 39.94 22.34]  Type: <class 'numpy.ndarray'>


### Question # 1:  
In the array given:
- Find the index for the element of value 2
- Find its shape, size, type and dtype
- Slice the array to create a 2x2 array with elements 30, 40, 300 and 400
- Slice the array to get elements from column at index 2 onwards and all rows
- Slice the array to get elements from row at index 1 onwards and all columns
- Slice the array to get all columns and only top two rows
- Slice the array to get row at index 2 and columns at index 1 and 2 only only

Print all answers to output

[Note: Create new variables of your choice as needed.]

In [4]:
a = np.array([[1, 2, 3, 4], [10, 20, 30, 40], [100, 200, 300, 400]])

# ------- type the answer below this line ------- #

# Answer # 1:
#--> 2 is at row index#0 and column index#1
print("Index of element 2 is: a[0,1]")
print("\n")

# Answer # 2:
a_shape = a.shape
a_size = a.size
a_type = type(a)
a_dtype = a.dtype
print("Shape:", a_shape, " Size:",a_size, " Type:", a_type, " dtype:", a_dtype)
print("\n")

# Answer # 3:
a_new = a[1:, 2:]
print('Array: \n', a_new)
print("\n")

# Answer # 4:
a_cols = a[:, 2:]
print('Array for index#2 columns and all rows: \n', a_cols)
print("\n")

# Answer # 5:
a_rows = a[1:, :]
print('Array for index#1 row and all columns: \n', a_rows)
print("\n")

# Answer # 6:
a_slice = a[0:2,:]
print("Array with top two rows and all columns: \n", a_slice)
print("\n")

# Answer # 7:
a_slice2 = a[2, 1:3]
print("Array with row at index#2 and columns with index# 1 and 2:\n", a_slice2)
print("\n")

Index of element 2 is: a[0,1]


Shape: (3, 4)  Size: 12  Type: <class 'numpy.ndarray'>  dtype: int64


Array: 
 [[ 30  40]
 [300 400]]


Array for index#2 columns and all rows: 
 [[  3   4]
 [ 30  40]
 [300 400]]


Array for index#1 row and all columns: 
 [[ 10  20  30  40]
 [100 200 300 400]]


Array with top two rows and all columns: 
 [[ 1  2  3  4]
 [10 20 30 40]]


Array with row at index#2 and columns with index# 1 and 2:
 [200 300]




### Question # 2: 
- Compute the elementwise sum of two arrays below
- Compute the elementwise multiplication of two arrays below
- Use two arrays given to compute an output array np.array([[0.1 , 0.2 ],[0.05, 0.1 ]])

Print all answers to output

[Note: Create new variables of your choice as needed.]

In [14]:
p1 = np.array([[1,2], [1,2]])
p2 = np.array([[10, 10], [20, 20]])


# ------- type the answer below this line ------- #

# Answer # 1:
a_sum = p1 + p2
print("Elementwise sum: \n", a_sum)
print("\n")

# Answer # 2:
a_multi = p1 * p2
print("Elementwise multiplication: \n", a_multi)
print("\n")

# Answer # 3:
a_find = p1 / p2
print("Array is: \n", a_find)

Elementwise sum: 
 [[11 12]
 [21 22]]


Elementwise multiplication: 
 [[10 20]
 [20 40]]


Array is: 
 [[0.1  0.2 ]
 [0.05 0.1 ]]


### Question # 3:
- Find the index for the min and max numbers in the array along axis=0 and axis=1 
- Create a subset of the array as: np.array([[8,6],[2,11]]) (Hint: use slicing and square root)

Print all answers to output

[Note: Create new variables of your choice as needed.]

In [6]:
a = np.array([[1,22,3.4,56,9],
              [34,23,64,36,2],
              [6,8,4,121,6]
             ])

# ------- type the answer below this line ------- #

# Answer # 1:
a_min_idx_col = a.min(axis=1)
a_min_idx_row = a.min(axis=0)
a_max_idx_col = a.max(axis=1)
a_max_idx_row = a.max(axis=0)
print("For axis=0: Min: ", a_min_idx_row, " Max:", a_max_idx_row, "\n")
print("For axis=1: Min: ", a_min_idx_col, " Max:", a_max_idx_col)
print('\n')

# Answer # 2:
a_sliced = np.sqrt(a[1:,2:4])
print("Sliced and square root of array: \n", a_sliced)

For axis=0: Min:  [ 1.   8.   3.4 36.   2. ]  Max: [ 34.  23.  64. 121.   9.] 

For axis=1: Min:  [1. 2. 4.]  Max: [ 56.  64. 121.]


Sliced and square root of array: 
 [[ 8.  6.]
 [ 2. 11.]]


### Question # 4:
Imagine the array given below is the average customer rating data.
Here, each column represents day of the week and
each row represents the hotel chain in the Sky-city.
Assuming that you reach that Sky-city on a Wednesday, 
which hotel could you find that has the highest customer rating? 

Rating scale:
1(bad) ... to ... 5 (excellent)

Print all answers to output

[Note: Create new variables of your choice as needed.]

In [7]:
customer_rating = np.array([
    [3.5, 4.9, 2.3, 5.0, 1.0, 3.4, 4.4], # Hotel Panorama
    [0.5, 3.9, 1.3, 4.0, 5.0, 4.4, 2.4], # Hotel Galactica
    [4.5, 1.9, 3.3, 4.0, 5.0, 3.9, 2.3], # Hotel Noname
    [1.1, 3.9, 4.1, 3.9, 4.3, 4.7, 2.1], # Hotel Seaby
    [5.0, 5.0, 1.1, 1.1, 2.4, 4.9, 2.3], # Hotel Drive
    [4.5, 3.4, 3.3, 4.8, 4.4, 3.3, 3.1], # Hotel Paradise
   # Mon. Tue. Wed. Thu. Fri. Sat. Sun  
])
# ------- type the answer below this line ------- #
a = customer_rating[:,2] # Get the data for Wednesday
a_max_rating = a.max() # Get the highest customer rating for Wednesday
print("The highest average customer rating on Wednesday is ", a_max_rating, " for Hotel Seaby.")

The highest average customer rating on Wednesday is  4.1  for Hotel Seaby.


### Question # 5:

#### Story:
A new business'CrunchyRoads' in the city is in the final stages of a contract with one of five local airports.  
The contract would allow CrunchyRoads to get cheaper air-tickets for their employees.
They need to choose only one airport. The company also wishes to choose an airport that is closest to their headquarter. Because it would reduce the commute time for their staff and thus reduce travel cost. They have hired you as an analyst to find them a closest airport.

#### Your approach:
- In the array given below there are latitude and longitude for 5 airports
- Column at Index#0 is latitude and Index#1 is longitude [Hint: Here, think of this as x (latitude) and y (longitude) coordinates.]
- To calculate the distance between two points (x1,y1) and (x2,y2) the formula is: 
  - square root of (x2 - x2)**2 + (y2 - y1)**2
  

[Note: Solve without using a 'for loop'.]

Print all answers to output.

[Note: Create new variables of your choice as needed.]

In [13]:
airports_xy_cord = np.array([
    [10.5, 11.0], # Airport Superfast
    [5.9,15.6],   # Airport Timfly
    [13.8, 7.7],  # Airport Artsky
    [8.0,8.0],    # Airport Whereto
    [12.6,2.1]    # Airport Tonowhere
   # x.    y. 
])

crunchy_roads_cord = np.array([1,1]) # Office Headquarter
                            #. x y
# ------- type the answer below this line ------- #

a = (np.subtract(airports_xy_cord, crunchy_roads_cord))**2
b = a.sum(axis=1)**0.5
print(b)
print("Shortest distance is ", min(b), "\nAirport Whereto is closest to headquarter.")

[13.79311422 15.40032467 14.44749113  9.89949494 11.65203845]
Shortest distance is  9.899494936611665 
Airport Whereto is closest to headquarter.


### Hope you enjoyed the exercise. Thank you !!!

#### Please like, share and subscribe to learndataa 
-<html>https://www.youtube.com/channel/UCzUpHQAfj3ulmJkTAfBtXLw/</html>

In [27]:
#learndataa learndataa learndataa learndataa learndataa learndataa learndataa learndataa learndataa