In [ ]:
#learndataa learndataa learndataa learndataa learndataa learndataa learndataa learndataa learndataa

## Exercises

### For Beginners: 6. Arrays (Part II) in Python

#### Total questions sets: 6
#### Estimated time required: upto 120 minutes or more (Please take your time to understand and solve the questions.)

[Notes: 
- Answers may be typed after the line "#-------#" in each cell. Additional cells may be created if needed.
- The estimated time required to complete the exercise may vary depending on your prior knowledge.
- Answers to the questions are posted at the end of this worksheet. However, to help you learn, it is suggested that you to try to answer the questions yourself before looking at the answers.
]

### Import libraries

In [2]:
import numpy as np
import pandas as pd

### Question 0:

#### Story:
Our friend at MagicApples fruit store has given the data below for their weekly orders.
The store sells mangoes, apples, oranges and bananas.
- In the array 'fruits', the rows indicate day-of-week.
Whereas, columns indicate time during the day such as: morning, afternoon, evening and night
 - For example: On Monday morning they sell mangoes
- The array 'orders' is similar to fruits. It has weekly count of number of orders for each type of fruit.
 - For example: On Monday morning they sell '90' fruits.
- Together arrays 'fruits' and 'orders' tell number of orders i.e. fruits sold for each type of fruit.
 - For example: On Monday morning they sell '90' fruits that are 'mangoes'.

#### Requests:
- Use boolean conditions to filter the array 'fruits' to include only 'apples' in the output. The length of that output array would tell how many times during a week the store sells apples. So how many times was it?
- Using boolean conditions find the time of day when the orders are lowest on a Thursday.
- Using the array 'order' find the day-of-week, that has highest number of orders in total.
- Using the array 'order find the time of day that has the lowest orders in total.

Print all answers to output

[Note: Create new variables of your choice as needed.]

In [ ]:
fruits = np.array([['mangoes', 'apples', 'oranges', 'bananas'], # Monday
                   ['apples', 'apples', 'mangoes', 'bananas'],  # Tuesday
                   ['oranges', 'oranges', 'bananas', 'mangoes'],# Wednesday
                   ['apples', 'apples', 'mangoes', 'mangoes'],   # Thursday
                   ['mangoes', 'apples', 'oranges', 'bananas'], # Friday
                   ['apples', 'apples', 'mangoes', 'bananas'],  # Saturday
                   ['oranges', 'oranges', 'bananas', 'mangoes'] # Sunday
              #.  morning(m). afternoon(a) evening(e). night(n)
             ])

order = np.array([[90,100,20,80], # Monday
                   [80,110,30,90], # Tuesday
                   [120,90,34,82], # Wednesday
                   [99,130,10,92], # Thursday
                   [94,112,23,96], # Friday
                   [88,101,29,89], # Saturday
                   [76,85,35,100]  # Sunday
                #  (m)(a) (e)(n)
                  ])

# ------- type the answer below this line ------- #



### Question # 1:  
Please use the same arrays from Question#0, here.

Our friend at MagicApples would like to know:
- How many times in a week does the store sell mangoes? (Hint: Use the fruits array)
- On weekends (i.e. Saturday and Sunday), what is the ranking of the fruits ordered i.e. which fruit sold highest to lowest? (Hint: Use indexing)
- Are the orange orders especially low certain time of the day?

Print all answers to output

[Note: Create new variables of your choice as needed.]

In [ ]:
# Use the arrays 'fruits' and 'orders' from Question#0 above.

# ------- type the answer below this line ------- #



### Question # 2: 
The array 'price' below gives selling price of each fruit sold on a specific day (i.e. array 'orders' in Question#0)
- Find the total revenue generated by the store on each week day (Hint: Use the array 'order' that has number of fruits sold during a day)
- Array 'percent_cost_increase' gives the percentage increase in cost of each fruit on a specific time of weekday. Using this array and the 'price' array, calculate the new price of fruits after the hike. Store this in a new variable 'new_price'
(Hint: 10% increase in price, of say \\$50 would be = \\$50*(1 + (10/100)) = $55.)
- Calculate total revenue after price increase and also print the total revenue before price increase.

Print all answers to output

[Note: Create new variables of your choice as needed.]

In [ ]:
price = np.array([ [1.0,1.1,0.6,1.3], # Monday
                   [0.9,1.2,0.7,1.4], # Tuesday
                   [1.2,0.9,0.3,0.9], # Wednesday
                   [1.1,0.8,0.4,1.2], # Thursday
                   [0.9,1.3,0.4,1.5], # Friday
                   [0.8,1.2,1.1,2.0], # Saturday
                   [1.3,1.1,0.7,1.5]  # Sunday
                #  (m)(a) (e)(n)
                  ])

percent_cost_increase = np.array([ 
                   [37,50,11,29], # Monday
                   [33,45,10,30], # Tuesday
                   [32,46,9,32], # Wednesday
                   [39,54,12,33], # Thursday
                   [34,55,13,31], # Friday
                   [33,56,14,34], # Saturday
                   [35,58,12,33]  # Sunday
                #  (m)(a) (e)(n)
                  ])

# ------- type the answer below this line ------- #




### Question # 3:
- Print the shape of array 'a' below. 
- Then, reduce the dimensions of the array using .squeeze(). And print new array shape.
- Now, reshape the array to (5,3) and store in a new variable 'x
- Next, flatten the array 'x' to create a 1D array
- Find the number of elements in this 1D array and the sum of all the elements
- Create another array 'b' using random numbers of shape ((3,7). 
- Find the dot product between x and b

Print all answers to output

[Note: Create new variables of your choice as needed.]

In [ ]:
a = np.array([[[[9.1,2.2,3.4,5,4.9],
              [3.4,2.3,6.4,3.6,2.0],
              [6.5,8.6,4.4,1.2,6.7]]]]
             )

# ------- type the answer below this line ------- #



### Question # 4:
- Split the array 'z' into two arrays of same shape. (Hint: horizontal)
- Use broadcasting to multiply each element of the array 'z' by 1000 store this in a new variable 'y'
- Create a new array 'z2' such that elementwise sum of z+z1=0


Print all answers to output

[Note: Create new variables of your choice as needed.]

In [8]:
z = np.array([
    [3.5, 4.9, 2.3, 5.0, 1.0, 3.4, 4.4], 
    [0.5, 3.9, 1.3, 4.0, 5.0, 4.4, 2.4], 
    [4.5, 1.9, 3.3, 4.0, 5.0, 3.9, 2.3], 
    [1.1, 3.9, 4.1, 3.9, 4.3, 4.7, 2.1], 
    [5.0, 5.0, 1.1, 1.1, 2.4, 4.9, 2.3], 
    [4.5, 3.4, 3.3, 4.8, 4.4, 3.3, 3.1], 
])
# ------- type the answer below this line ------- #

# Answer#1:
z_slice_1 = z[0:3,:]
z_slice_2 = z[3:,:]
print('z_slice_1:\n',z_slice_1, '\nz_slice_1:\n',z_slice_2)
print("\n")

# Answer#2:
y = z*1000
print("y:\n",y)
print("\n")

# Answer#3:
z2 = -1*z
z_plus_z2 = z+z2
sum_z_z2 = np.sum(z_plus_z2)
print("z2:\n",z2,"\nz_plus_z2:", z_plus_z2, "\nSum z and z2: ", sum_z_z2)

z_slice_1:
 [[3.5 4.9 2.3 5.  1.  3.4 4.4]
 [0.5 3.9 1.3 4.  5.  4.4 2.4]
 [4.5 1.9 3.3 4.  5.  3.9 2.3]] 
z_slice_1:
 [[1.1 3.9 4.1 3.9 4.3 4.7 2.1]
 [5.  5.  1.1 1.1 2.4 4.9 2.3]
 [4.5 3.4 3.3 4.8 4.4 3.3 3.1]]


y:
 [[3500. 4900. 2300. 5000. 1000. 3400. 4400.]
 [ 500. 3900. 1300. 4000. 5000. 4400. 2400.]
 [4500. 1900. 3300. 4000. 5000. 3900. 2300.]
 [1100. 3900. 4100. 3900. 4300. 4700. 2100.]
 [5000. 5000. 1100. 1100. 2400. 4900. 2300.]
 [4500. 3400. 3300. 4800. 4400. 3300. 3100.]]


z2:
 [[-3.5 -4.9 -2.3 -5.  -1.  -3.4 -4.4]
 [-0.5 -3.9 -1.3 -4.  -5.  -4.4 -2.4]
 [-4.5 -1.9 -3.3 -4.  -5.  -3.9 -2.3]
 [-1.1 -3.9 -4.1 -3.9 -4.3 -4.7 -2.1]
 [-5.  -5.  -1.1 -1.1 -2.4 -4.9 -2.3]
 [-4.5 -3.4 -3.3 -4.8 -4.4 -3.3 -3.1]] 
z_plus_z2: [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]] 
Sum z and z2:  0.0


### Question # 5:

Our friend at MagicApples says they can stack boxes of fruits, so can you stack arrays? Let's do it:
- Stack arrays m1, m2, m3, m4 ad m5 to create a (5,4) dimensional array and store in variable 'm_new'
- Then stack the array 'm_new' horizontally to create (5,8) dimensional array and store in another variable 'm_new2'

Print all answers to output.

[Note: Create new variables of your choice as needed.]

In [10]:
m1 = np.array([1,2,3,4])
m2 = np.array([10,20,30,40])
m3 = np.array([100,200,300,400])
m4 = np.array([1000,2000,3000,4000])
m5 = np.array([10000,20000,30000,40000])

# ------- type the answer below this line ------- #



### ////////////////////////////////////////////////////////////////////////////////////////////////////////
### ////////////////////////////////////////////////////////////////////////////////////////////////////////
### For practice, please try the questions above before looking at the answers below
### ////////////////////////////////////////////////////////////////////////////////////////////////////////
### ////////////////////////////////////////////////////////////////////////////////////////////////////////

# Answers
[Note: There may be different ways to answer the same question. Therefore, it is okay if the answers vary and sometimes do not match exactly.]

### Question 0:

#### Story:
Our friend at MagicApples fruit store has given the data below for their weekly orders.
The store sells mangoes, apples, oranges and bananas.
- In the array 'fruits', the rows indicate day-of-week.
Whereas, columns indicate time during the day such as: morning, afternoon, evening and night
 - For example: On Monday morning they sell mangoes
- The array 'orders' is similar to fruits. It has weekly count of number of orders for each type of fruit.
 - For example: On Monday morning they sell '90' fruits.
- Together arrays 'fruits' and 'orders' tell number of orders i.e. fruits sold for each type of fruit.
 - For example: On Monday morning they sell '90' fruits that are 'mangoes'.

#### Requests:
- Use boolean conditions to filter the array 'fruits' to include only 'apples' in the output. The length of that output array would tell how many times during a week the store sells apples. So how many times was it?
- Using boolean conditions find the time of day when the orders are lowest on a Thursday.
- Using the array 'order' find the day-of-week, that has highest number of orders in total.
- Using the array 'order find the time of day that has the lowest orders in total.

Print all answers to output

[Note: Create new variables of your choice as needed.]

In [3]:
fruits = np.array([['mangoes', 'apples', 'oranges', 'bananas'], # Monday
                   ['apples', 'apples', 'mangoes', 'bananas'],  # Tuesday
                   ['oranges', 'oranges', 'bananas', 'mangoes'],# Wednesday
                   ['apples', 'apples', 'mangoes', 'mangoes'],   # Thursday
                   ['mangoes', 'apples', 'oranges', 'bananas'], # Friday
                   ['apples', 'apples', 'mangoes', 'bananas'],  # Saturday
                   ['oranges', 'oranges', 'bananas', 'mangoes'] # Sunday
              #.  morning(m). afternoon(a) evening(e). night(n)
             ])

order = np.array([[90,100,20,80], # Monday
                   [80,110,30,90], # Tuesday
                   [120,90,34,82], # Wednesday
                   [99,130,10,92], # Thursday
                   [94,112,23,96], # Friday
                   [88,101,29,89], # Saturday
                   [76,85,35,100]  # Sunday
                #  (m)(a) (e)(n)
                  ])

# ------- type the answer below this line ------- #

# Answer # 1:
apples_only = fruits[fruits=='apples']
times_apples_sold = len(apples_only)
print('Apples were sold %d times a week.' %(times_apples_sold))
print("\n")

# Answer # 2:
lowest_orders_thu = min(order[3,:])
print('On Thursday the lowest sales of fruits was ', lowest_orders_thu)
print('Visually looking at the array, this number %d was during the "evening".' %(lowest_orders_thu))
print("\n")

# Answer # 3:
highest_orders_day = np.sum(order, axis=1)
print("Highest orders were equal to ", np.max(highest_orders_day), ' in ', highest_orders_day)
print("Visually looking at the array, this was the row for 'Wednesday'.")
print("\n")

# Answer # 4:
lowest_orders_in_day = np.sum(order, axis=0)
print("Highest orders were equal to ", np.min(lowest_orders_in_day), ' in ', lowest_orders_in_day)
print("Visually looking at the array, this was the row for 'evening'.")


Apples were sold 8 times a week.


On Thursday the lowest sales of fruits was  10
Visually looking at the array, this number 10 was during the "evening".


Highest orders were equal to  331  in  [290 310 326 331 325 307 296]
Visually looking at the array, this was the row for 'Wednesday'.


Highest orders were equal to  181  in  [647 728 181 629]
Visually looking at the array, this was the row for 'evening'.


### Question # 1:  
Please use the same arrays from Question#0, here.

Our friend at MagicApples would like to know:
- How many times in a week does the store sell mangoes? (Hint: Use the fruits array)
- On weekends (i.e. Saturday and Sunday), what is the ranking of the fruits ordered i.e. which fruit sold highest to lowest? (Hint: Use indexing)
- Are the orders especially low certain time of the day?

Print all answers to output

[Note: Create new variables of your choice as needed.]

In [4]:
# Use the arrays 'fruits' and 'orders' from Question#0 above.

# ------- type the answer below this line ------- #


# Answer # 1:
mangoes_only = fruits[fruits=='mangoes']
times_mangoes_sold = len(mangoes_only)
print('Mangoes were sold %d times a week.' %(times_mangoes_sold))
print("\n")

# Answer # 2:
sat_sun_fruits = fruits[5:,:]
sat_sun_order = order[5:,:]
sat_sun_apples = sat_sun_order[sat_sun_fruits=='apples'].sum()
sat_sun_mangoes = sat_sun_order[sat_sun_fruits=='mangoes'].sum()
sat_sun_oranges = sat_sun_order[sat_sun_fruits=='oranges'].sum()
sat_sun_bananas = sat_sun_order[sat_sun_fruits=='bananas'].sum()
print("Apples:",sat_sun_apples, " Mangoes:",sat_sun_mangoes, " Oranges:", sat_sun_oranges, " Bananas:", sat_sun_bananas )
print("Visually looking at above numbers, the ranking is:\nApples:189 \nOranges:161 \nMangoes:129 \nBananas:124")
print("\n")

# Answer # 3:
oranges = order.copy()
oranges[fruits!='oranges']=0
oranges_order = oranges.sum(axis=0)
print("Orders for oranges [Mon --> Sun]: ", oranges_order)
print("Visually looking at the above numbers, %d oranges are sold in the 'evening'. And highest %d in the 'morning'" %(oranges_order[3], oranges_order[0]))




Mangoes were sold 8 times a week.


Apples: 189  Mangoes: 129  Oranges: 161  Bananas: 124
Visually looking at above numbers, the ranking is:
Apples:189 
Oranges:161 
Mangoes:129 
Bananas:124


Orders for oranges [Mon --> Sun]:  [196 175  43   0]
Visually looking at the above numbers, 0 oranges are sold in the 'evening'. And highest 196 in the 'morning'


### Question # 2: 
The array 'price' below gives selling price of each fruit sold on a specific day (i.e. array 'order' in Question#0)
- Find the total revenue generated by the store on each week day (Hint: Use the array 'order' that has number of fruits sold during a day)
- Array 'percent_cost_increase' gives the percentage increase in cost of each fruit on a specific time of weekday. Using this array and the 'price' array, calculate the new price of fruits after the hike. Store this in a new variable 'new_price'
(Hint: 10% increase in price, of say \\$50 would be = \\$50*(1 + (10/100)) = $55.)
- Calculate total revenue after price increase and also print the total revenue before price increase.

Print all answers to output

[Note: Create new variables of your choice as needed.]

In [5]:
price = np.array([ [1.0,1.1,0.6,1.3], # Monday
                   [0.9,1.2,0.7,1.4], # Tuesday
                   [1.2,0.9,0.3,0.9], # Wednesday
                   [1.1,0.8,0.4,1.2], # Thursday
                   [0.9,1.3,0.4,1.5], # Friday
                   [0.8,1.2,1.1,2.0], # Saturday
                   [1.3,1.1,0.7,1.5]  # Sunday
                #  (m)(a) (e)(n)
                  ])

percent_cost_increase = np.array([ 
                   [37,50,11,29], # Monday
                   [33,45,10,30], # Tuesday
                   [32,46,9,32], # Wednesday
                   [39,54,12,33], # Thursday
                   [34,55,13,31], # Friday
                   [33,56,14,34], # Saturday
                   [35,58,12,33]  # Sunday
                #  (m)(a) (e)(n)
                  ])

# ------- type the answer below this line ------- #


# Answer#1:
revenue = price*order
week_day_revenue = revenue.sum(axis=1)
print("The revenue generated on each day [Mon --> Sun] is: ]: ", week_day_revenue)
print("\n")

# Answer#2:
new_price = price*(1+(percent_cost_increase/100))
new_revenue = new_price*order
total_revenue_after = new_revenue.sum()
total_revenue_before = np.sum(price*order)
print("new_price:\n", new_price)
print("\n")
print("Total revenue before price increase was: ", total_revenue_before)
print("New total revenue after price increase is: ", total_revenue_after)




The revenue generated on each day [Mon --> Sun] is: ]:  [316.  351.  309.  327.3 383.4 401.5 366.8]


new_price:
 [[1.37  1.65  0.666 1.677]
 [1.197 1.74  0.77  1.82 ]
 [1.584 1.314 0.327 1.188]
 [1.529 1.232 0.448 1.596]
 [1.206 2.015 0.452 1.965]
 [1.064 1.872 1.254 2.68 ]
 [1.755 1.738 0.784 1.995]]


Total revenue before price increase was:  2455.0
New total revenue after price increase is:  3393.277


### Question # 3:
- Print the shape of array 'a' below. 
- Then, reduce the dimensions of the array using .squeeze(). And print new array shape.
- Now, reshape the array to (5,3) and store in a new variable 'x
- Next, flatten the array 'x' to create a 1D array
- Find the number of elements in this 1D array and the sum of all the elements
- Create another array 'b' using random numbers of shape ((3,7). 
- Find the dot product between x and b

Print all answers to output

[Note: Create new variables of your choice as needed.]

In [7]:
a = np.array([[[[9.1,2.2,3.4,5,4.9],
              [3.4,2.3,6.4,3.6,2.0],
              [6.5,8.6,4.4,1.2,6.7]]]]
             )

# ------- type the answer below this line ------- #

a = np.array([[[[9.1,2.2,3.4,5,4.9],
              [3.4,2.3,6.4,3.6,2.0],
              [6.5,8.6,4.4,1.2,6.7]]]]
             )

# ------- type the answer below this line ------- #

# Answer#1:
print('Shape of array "a" is: ', a.shape)
print('\n')

# Answer#2:
a = np.squeeze(a)
print('Shape of array "a" is: ', a.shape)
print("\n")

# Answer#3:
x = a.reshape(5,3)
print("x:\n",x)
print("\n")

# Answer#4:
x_flatten = x.flatten()
print("Flattened x: \n", x_flatten)
print("\n")

# Answer#5:
num_x = len(x_flatten)
sum_x = np.sum(x_flatten)
print("Number of elements in x: ", num_x, "\nSum of x: ", sum_x)
print("\n")

# Answer#6:
b = np.random.random((3,7))
print("b:\n",b)
print("\n")

# Answer#7:
x_dot_b = np.dot(x,b)
print("x dot b:\n", x_dot_b)

Shape of array "a" is:  (1, 1, 3, 5)


Shape of array "a" is:  (3, 5)


x:
 [[9.1 2.2 3.4]
 [5.  4.9 3.4]
 [2.3 6.4 3.6]
 [2.  6.5 8.6]
 [4.4 1.2 6.7]]


Flattened x: 
 [9.1 2.2 3.4 5.  4.9 3.4 2.3 6.4 3.6 2.  6.5 8.6 4.4 1.2 6.7]


Number of elements in x:  15 
Sum of x:  69.7


b:
 [[0.76211458 0.79075507 0.62727516 0.48804355 0.5219963  0.8296133
  0.98183838]
 [0.40053447 0.15045575 0.72774054 0.08844024 0.10428919 0.19335767
  0.56473928]
 [0.58326479 0.09303371 0.84771035 0.49240851 0.00540772 0.45069008
  0.62800898]]


x dot b:
 [[ 9.7995188   7.84318844 10.19144834  6.30995379  4.99798878  9.50721413
  12.31238618]
 [ 7.75629209  5.00732318  9.58451963  4.54776387  3.13938479  6.62786532
   9.81164491]
 [ 6.41603738  3.11657486  9.15202958  3.46118835  1.88751013  4.76808394
   8.13339201]
 [ 9.14378039  3.35956246 13.27517281  5.78566187  1.76837878  6.79198614
  11.03535935]
 [ 7.7418196   4.28319509  9.31295868  5.55265696  2.45816249  6.90195126
   9.20543618]]


### Question # 4:
- Multiply the array 'z' into two arrays of same shape
- Use broadcasting to multiply each element of the array by 1000 store this in a new variable 'y'
- Create a new array 'z2' such that elementwise sum of z+z1=0


Print all answers to output

[Note: Create new variables of your choice as needed.]

In [ ]:
z = np.array([
    [3.5, 4.9, 2.3, 5.0, 1.0, 3.4, 4.4], 
    [0.5, 3.9, 1.3, 4.0, 5.0, 4.4, 2.4], 
    [4.5, 1.9, 3.3, 4.0, 5.0, 3.9, 2.3], 
    [1.1, 3.9, 4.1, 3.9, 4.3, 4.7, 2.1], 
    [5.0, 5.0, 1.1, 1.1, 2.4, 4.9, 2.3], 
    [4.5, 3.4, 3.3, 4.8, 4.4, 3.3, 3.1], 
])
# ------- type the answer below this line ------- #



### Question # 5:

Our friend at MagicApples says they can stack boxes of fruits, so can you stack arrays? Let's do it:
- Stack arrays m1, m2, m3, m4 ad m5 to create a (5,4) dimensional array and store in variable 'm_new'
- Then stack the array 'm_new' horizontally to create (5,8) dimensional array and store in another variable 'm_new2'

Print all answers to output.

[Note: Create new variables of your choice as needed.]

In [11]:
m1 = np.array([1,2,3,4])
m2 = np.array([10,20,30,40])
m3 = np.array([100,200,300,400])
m4 = np.array([1000,2000,3000,4000])
m5 = np.array([10000,20000,30000,40000])

# ------- type the answer below this line ------- #

m1 = np.array([1,2,3,4])
m2 = np.array([10,20,30,40])
m3 = np.array([100,200,300,400])
m4 = np.array([1000,2000,3000,4000])
m5 = np.array([10000,20000,30000,40000])

# ------- type the answer below this line ------- #


# Answer#1:
m_new = np.vstack([m1,m2,m3,m4,m5])
print("m_new:\n", m_new, "\nShape:", m_new.shape)
print("\n")

# Answer#2:
m_new2 = np.hstack([m_new,m_new])
print("m_new2:\n", m_new2, "\nShape:", m_new2.shape)

print("Yes! we can stack arrays!")


m_new:
 [[    1     2     3     4]
 [   10    20    30    40]
 [  100   200   300   400]
 [ 1000  2000  3000  4000]
 [10000 20000 30000 40000]] 
Shape: (5, 4)


m_new2:
 [[    1     2     3     4     1     2     3     4]
 [   10    20    30    40    10    20    30    40]
 [  100   200   300   400   100   200   300   400]
 [ 1000  2000  3000  4000  1000  2000  3000  4000]
 [10000 20000 30000 40000 10000 20000 30000 40000]] 
Shape: (5, 8)
Yes! we can stack arrays!


# Congratulations on completing the exercise!

### Hope you enjoyed the questions. Thank you !!!

#### Please like, share and subscribe to learndataa 
-<html>https://www.youtube.com/channel/UCzUpHQAfj3ulmJkTAfBtXLw/</html>

In [27]:
#learndataa learndataa learndataa learndataa learndataa learndataa learndataa learndataa learndataa